"""empty message

Revision ID: 512521e8a4da
Revises: 4db800314953
Create Date: 2024-06-05 22:05:04.752958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512521e8a4da'
down_revision: Union[str, None] = '4db800314953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
