"""empty message

Revision ID: c520341f1115
Revises: 
Create Date: 2024-05-26 14:06:29.201018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c520341f1115'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('devices', 'scale_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('scale_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('devices', 'value')
    # ### end Alembic commands ###
